import sys

"""
A quick little function to strip off some of the unneed in the server map
that is generated by server_conf.sh
"""

if __name__ ==  '__main__':
    my_path = sys.argv[1].split('/')[:-1]
    file_name = sys.argv[2]
    server_paths = []
    with open(file_name, 'r') as r:
        paths = r.read().split('\n')
        for line in paths:
            server_paths += [line.split('/')[len(my_path):]]
    with open(file_name, 'w') as w:
        for line in server_paths:
            if len(line) > 0:
                w.write('/'.join(line))
                w.write('\n')
